# ./project-1/docker-compose.yml

version: "3.9"

services:
  app:
    build: .
    container_name: project-1-app
    volumes:
      - .:/app
    working_dir: /app
    command: python src/main.py
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
